# Generated by Django 5.2.17 on 2026-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='nombre_proveedor', max_length=150)),
                ('pais', models.CharField(db_column='pais_proveedor', max_length=100)),
                ('contacto', models.CharField(db_column='contacto_proveedor', max_length=150)),
                ('telefono', models.CharField(db_column='telefono_proveedor', max_length=50)),
                ('email', models.EmailField(db_column='correo_proveedor', max_length=150)),
                ('direccion', models.CharField(db_column='direccion_proveedor', max_length=255)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre_empresa'],
                'managed': False,
            },
        ),
    ]
