# Generated by Django 5.2.17 on 2026-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='direccion',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('cliente',), name='unique_principal_address_per_client'),
        ),
    ]
