# Generated by Django 5.2.17 on 2026-10-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_direccion_unique_principal_address_per_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'ordering': ['razon_social'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'managed': False, 'ordering': ['-principal', 'nombre'], 'verbose_name': 'dirección', 'verbose_name_plural': 'direcciones'},
        ),
    ]
