# Generated by Django 5.2.17 on 2026-10-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
